---
title: Gravitee.io API Platform Documentation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tooltips:
    title: Tooltips
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    comments: true
    search: true
    sidebar: home_sidebar
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-asciidoc
description: Home page for Gravitee.io API Platform documentation
summary: Gravitee.io API Platform documentation
keywords: Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid,
  documentation, manual, guide, reference, api, alert, alerting, engine
twitter:
  username: graviteeio
output: web
topnav_title: Gravitee.io API Platform
site_title: Gravitee.io API Platform Documentation
company_name: GraviteeSource
github_editme_path: 
disqus_shortname: 
host: 127.0.0.1
port: 4000
exclude:
- ".idea/"
- ".gitignore"
- README.adoc
- CONTRIBUTING.adoc
- src/
feedback_subject_line: 
feedback_email: 
feedback_disable: true
google_analytics: UA-67690250-1
newsletter_api: https://newsletter.gravitee.io/
sidebars:
- apim_sidebar
- am_sidebar
- ae_sidebar
- cli_sidebar
- ee_sidebar
- cockpit_sidebar
url: https://docs.gravitee.io
products:
  apim:
    _1x:
      version: 1.30.31
    _3x:
      version: 3.9.1
    ee:
      version: 3.9.1
  am:
    version: 3.9.1
    ee:
      version: 3.9.1
  ae:
    version: 1.3.1
    name: Gravitee.io Alert Engine (AE)
  cli:
    version: 0.3
  cockpit:
    version: 1.3
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
  - doctype=book
  - idseparator=_
  - icons=font
  - allow-uri-read=true
  - imagesdir=/images/
  - source-highlighter=rouge
  - rouge-css=class
  - stylesdir=css
